"""Serialize a FixPlan three ways: YAML rules, a runnable Python transform, and a
human-readable template rewrite.
"""

from __future__ import annotations

import pprint

import yaml

from cachetrace.core.attribute.paths import path_value
from cachetrace.core.fix import FixPlan


def emit_yaml(plan: FixPlan) -> str:
    doc = {
        "cachetrace_fix": {
            "model": plan.model,
            "projected_hit_rate": round(plan.projected_hit_rate, 4),
            "actual_hit_rate": round(plan.actual_hit_rate, 4),
            "rules": [
                {
                    "target": r.target,
                    "role": r.role,
                    "cause": r.cause,
                    "action": r.action,
                    "pattern": r.pattern,
                    "replacement": r.replacement,
                    "est_tokens_saved": r.est_tokens_saved,
                    "detail": r.detail,
                }
                for r in plan.rules
            ],
        }
    }
    return yaml.safe_dump(doc, sort_keys=False, width=100)


_PY_HEADER = '''"""Auto-generated by cachetrace `fix`. Canonicalizes requests to maximize prefix
cache hits. Drop this in front of your LLM calls (chat-completions message list).

Projected prefix-cache hit rate after applying: {proj:.0%} (was {act:.0%}).
Review before shipping — `remove`/`hoist` rules change what the model sees.
"""

from __future__ import annotations

import re

RULES = {rules}


def canonicalize(messages, tools=None):
    """Return (messages, tools) rewritten to maximize shared prefixes.

    - sort: deterministically orders the tool list
    - remove: strips volatile metadata (ids, counters) from the prefix
    - hoist: moves volatile spans (timestamps) to a trailing message
    """
    messages = [dict(m) for m in messages]
    hoisted = []

    for rule in RULES:
        if rule["action"] == "sort" and rule["target"] == "tools" and tools:
            tools = sorted(tools, key=lambda t: (t.get("function", t).get("name", "")))
            continue
        pattern = rule.get("pattern")
        if not pattern:
            continue
        rx = re.compile(pattern, re.DOTALL)
        for m in messages:
            if rule.get("role") and m.get("role") != rule["role"]:
                continue
            content = m.get("content")
            if not isinstance(content, str):
                continue
            if rule["action"] == "hoist":
                for match in rx.finditer(content):
                    hoisted.append(match.group("vol"))
            m["content"] = rx.sub(rule["replacement"], content)

    if hoisted:
        # Append to the very end of the prompt so the static prefix still caches
        # while the model still sees the value.
        tail = " [context: " + " ".join(hoisted) + "]"
        if messages and isinstance(messages[-1].get("content"), str):
            messages[-1]["content"] = messages[-1]["content"] + tail
        else:
            messages.append({{"role": "user", "content": tail.strip()}})
    return messages, tools
'''


def emit_python(plan: FixPlan) -> str:
    rules = [
        {
            "target": r.target,
            "role": r.role,
            "cause": r.cause,
            "action": r.action,
            "pattern": r.pattern,
            "replacement": r.replacement,
        }
        for r in plan.rules
    ]
    return _PY_HEADER.format(
        proj=plan.projected_hit_rate,
        act=plan.actual_hit_rate,
        rules=pprint.pformat(rules, indent=4, width=100, sort_dicts=False),
    )


def emit_rewrite(plan: FixPlan) -> str:
    """A readable before/after of the representative family's volatile segments."""
    if plan.representative is None:
        return "No multi-request template family found to rewrite."
    from cachetrace.core.fix.canonicalize import canonicalize_request

    fam = plan.representative
    ref = fam.family.requests[0]
    after_req = canonicalize_request(ref, fam)

    lines: list[str] = [f"# Template rewrite (family of {fam.family.size} requests)\n"]
    causes = ", ".join(sorted({s.cls.cause for s in fam.normalizable}))
    for path in fam.decomp:
        before = path_value(ref, path)
        after = path_value(after_req, path)
        if before == after:
            continue
        lines.append(f"## {path}")
        lines.append(f"  before: {_trunc(before)}")
        lines.append(f"  after:  {_trunc(after)}\n")

    tool_spans = [s for s in fam.normalizable if s.path == "tools"]
    if tool_spans:
        lines.append("## tools")
        lines.append(f"  before: {' '.join(t.name for t in ref.tools)}")
        lines.append(f"  after:  {' '.join(t.name for t in sorted(ref.tools, key=lambda t: t.name))} (sorted)\n")

    lines.append(f"Fixes: {causes}")
    lines.append(f"Projected hit rate: {plan.projected_hit_rate:.0%} (was {plan.actual_hit_rate:.0%})")
    return "\n".join(lines)


_ACTION_LABEL = {
    "timestamp": "hoist out of prefix",
    "uuid": "remove from prefix",
    "random_id": "remove from prefix",
    "counter": "remove from prefix",
    "reordering": "sort deterministically",
    "nondeterministic_json": "sort keys",
}


def _trunc(s: str, n: int = 120) -> str:
    s = s.replace("\n", "\\n")
    return s if len(s) <= n else s[: n - 1] + "…"
